

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/invoice_management?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: Coen275!
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-circular-references: true

  #    jndi-name: java:jboss/datasources/customers


  mail:
    host: smtp.gmail.com
    username: procodedemo@gmail.com
    password: ggqzkvmsuhdhhzwp
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



mail:
  fromMail:
    addr: procodedemo@gmail.com



server:
  port: 8888

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
